name: Main CI check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Main CI check
    runs-on: ubuntu-latest

    steps:
    - name: go env 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: branch
      uses: actions/checkout@v2

    - name: assert required test file exists
      run: |
        if [ -z "$(ls -A ./test)" ]; then
           echo "Test directory is empty"
           exit 1
        else
           echo "Test directory is not empty"
        fi

    - name: run fetcher tests
      run: go test ./test/internal/fetcher/...

    - name: run extractor tests
      run: go test ./test/internal/extractor
